name: Vanilife
version: '${version}'
main: net.azisaba.vanilife.Vanilife
api-version: '1.21'
depend:
  - CoreProtect
commands:
  block:
    description: Block any player.
    usage: /block <player>
  checkout:
    description: Process all subscriptions.
    usage: /checkout
  emote:
    description: Use any emote.
    usage: /emote <emote>
    aliases:
      - e
  enderchest:
    description: Open the ender chest.
    usage: /enderchest
    aliases:
      - ec
  feedback:
    description: Submit your feedback.
    usage: /feedback <details>
  filter:
    description: Edit the chat filter.
    usage: /filter <subcommand> [args…]
  friend:
    description: Send a friend request.
    usage: /friend <player>
    aliases:
      - f
  friendlist:
    description: View a list of your friends.
    usage: /friendlist [page]
    aliases:
      - fl
  housing:
    description: Teleport to Housing.
    usage: /housing
  jnkn:
    description: Send a janken request.
    usage: /jnkn <player>
    aliases:
      - janken
      - rock-paper-scissors
      - rps
  language:
    description: Change language.
    usage: /language <language>
    aliases:
      - lang
  mail:
    description: Send and check emails.
    usage: /mail [player] [subject] [message]
  mute:
    description: Mute any player.
    usage: /mute <player>
  nick:
    description: Sets the user's nickname.
    usage: /nick [name]
  plot:
    description: Open any plot menu.
    usage: /plot [plot]
  /plot:
    description: Command set for plot.
    usage: /plot <subcommand> [args…]
  poll:
    description: Create a poll.
    usage: /poll <option1> <option2> [options…]
  profile:
    description: View any player's profile.
    usage: /profile <player>
  ptp:
    description: Teleport to any plot.
    usage: /ptp <plot>
  report:
    description: Report the player.
    usage: /report <player> <details>
  rtp:
    description: Teleport to a random location.
    usage: /rtp
  sara:
    description: Set any player's sara.
    usage: /sara <player> <sara>
  service:
    description: Manage service configured on the Vanilife server.
    usage: /service <subcommand> [args…]
  settings:
    description: Edit settings in ばにらいふ.
    usage: /settings
    aliases:
      - config
      - setting
  store:
    description: Open the Vanilife store.
    usage: /store
  subscribe:
    description: Sign up for any subscription.
    usage: /subscribe <subscription>
  tpa:
    description: Accept teleport request.
    usage: /tpa <player>
  tpr:
    description: Send teleport request to any player.
    usage: /tpr <player>
  trade:
    description: Send a trade request.
    usage: /trade <player>
    aliases:
      - t
  trash:
    description: Open the Trash.
    usage: /trash
    aliases:
      - gomi
  unblock:
    description: Unblock any player.
    usage: /unblock <player>
  unmute:
    description: Unmute any player.
    usage: /unmute <player>
  unsubscribe:
    description: Cancel any subscription.
    usage: /unsubscribe <subscription>
  vote:
    description: Vote for any option.
    usage: /vote <poll> <option>
  vwm:
    description: Command set for Vanilife World Manager administrators.
    usage: /vwm <subcommand> [args…]
  wallet:
    description: Mola Management and Display.
    usage: /wallet [skill] [args…]
  world:
    description: Teleport to any world.
    usage: /world <world>
  worlds:
    description: Select the world you want to teleport.
    usage: /worlds