name: Vanilife
version: '${version}'
main: net.azisaba.vanilife.Vanilife
api-version: '1.21'
depend:
  - CoreProtect
commands:
  accept:
    description: Accept any request.
    usage: /accept <request>
  alert:
    description: Send an alert.
    usage: /alert <message>
  block:
    description: Block any player.
    usage: /block <player>
  chat:
    description: Creating chats, switching, messaging, and much more!
    usage: /chat [chat] [message]
    aliases:
      - c
      - ch
  /chat:
    description: Command set for chat.
    usage: //chat <subcommand> [args…]
    aliases:
      - /c
      - /ch
  checkout:
    description: Process all subscriptions.
    usage: /checkout
  domain:
    description: Open any domain menu.
    usage: /domain [domain]
  emote:
    description: Use any emote.
    usage: /emote <emote>
    aliases:
      - e
  enderchest:
    description: Open the ender chest.
    usage: /enderchest
    aliases:
      - ec
  feedback:
    description: Submit your feedback.
    usage: /feedback <details>
  filter:
    description: Edit the chat filter.
    usage: /filter <subcommand> [args…]
  friend:
    description: Send a friend request.
    usage: /friend <player>
    aliases:
      - f
  friendlist:
    description: View a list of your friends.
    usage: /friendlist [page]
    aliases:
      - fl
      - friends
  housing:
    description: Teleport to Housing.
    usage: /housing
  ime:
    description: Performs IME-related operations.
    usage: /ime <subcommand> [args…]
    aliases:
      - gomenne
      - gmn
      - henkan
  jail:
    description: Performs a jail on any player.
    usage: /jail <player>
  jnkn:
    description: Send a janken request.
    usage: /jnkn <player>
    aliases:
      - janken
      - rock-paper-scissors
      - rps
  language:
    description: Change language.
    usage: /language <language>
    aliases:
      - lang
  mail:
    description: Send and check emails.
    usage: /mail [player] [subject] [message]
  mute:
    description: Mute any player.
    usage: /mute <player>
  nick:
    description: Sets the user's nickname.
    usage: /nick [name]
  nkip:
    description: Vote for Nkip.
    usage: /nkip [world]
  osatou:
    description: Send a osatou request
    usage: /osatou <player>
    aliases:
      - sugar
  plot:
    description: Open any plot menu.
    usage: /plot [plot]
  /plot:
    description: Command set for plot.
    usage: /plot <subcommand> [args…]
  poll:
    description: Create a poll.
    usage: /poll <option1> <option2> [options…]
  profile:
    description: View any player's profile.
    usage: /profile <player>
    aliases:
      - p
      - bio
  ptp:
    description: Teleport to any plot.
    usage: /ptp <plot>
  referral:
    description: Issuance and use of referral codes.
    usage: /referral [player]
  realname:
    description: Displays the actual MCID of the player using the nickname.
    usage: /realname <nick>
  report:
    description: Report the player.
    usage: /report <player> <details>
  review:
    description: Submit Review.
    usage: /review <score>
  rtp:
    description: Teleport to a random location.
    usage: /rtp
  sara:
    description: Set any player's sara.
    usage: /sara <player> <sara>
  service:
    description: Manage service configured on the Vanilife server.
    usage: /service <subcommand> [args…]
  settings:
    description: Edit settings in ばにらいふ.
    usage: /settings
    aliases:
      - config
      - setting
  skin:
    description: Change your skin.
    usage: /skin <avatar>
  store:
    description: Open the Vanilife store.
    usage: /store
  su:
    description: Switch user permission.
    usage: /su
  subscribe:
    description: Sign up for any subscription.
    usage: /subscribe <subscription>
  sudo:
    description: Execute with higher-level user permission.
    usage: /sudo <command>
  togglechat:
    description: Enable or disable chat.
    usage: /togglechat
  tpa:
    description: Accept teleport request.
    usage: /tpa <player>
  tpr:
    description: Send teleport request to any player.
    usage: /tpr <player>
  trade:
    description: Send a trade request.
    usage: /trade <player>
    aliases:
      - t
  trash:
    description: Open the Trash.
    usage: /trash
    aliases:
      - gomi
  trickortreat:
    description: Trick or Treat!
    usage: /trickortreat
  tutorial:
    description: Start Tutorial.
    usage: /tutorial
    aliases:
      - book
  unblock:
    description: Unblock any player.
    usage: /unblock <player>
  unfriend:
    description: Unfriend any friend.
    usage: /unfriend <friend>
  unjail:
    description: Performs Jail release for any player.
    usage: /unjail <player>
  unmute:
    description: Unmute any player.
    usage: /unmute <player>
  unsubscribe:
    description: Cancel any subscription.
    usage: /unsubscribe <subscription>
  unwatch:
    description: Disable Watch mode.
    usage: /unwatch
  vote:
    description: Vote for any option.
    usage: /vote <poll> <option>
  wallet:
    description: Mola Management and Display.
    usage: /wallet [skill] [args…]
  warn:
    description: Send an warn.
    usage: /warn <player> <message>
  watch:
    description: Enable Watch mode.
    usage: /watch
  web:
    description: Browse the Web.
    usage: /web [url]
    aliases:
      - edge
      - chrome
      - firefox
      - safari
  wiki:
    description: Check the Wiki.
    usage: /wiki
  world:
    description: Teleport to any world.
    usage: /world <world>
  worlds:
    description: Select the world you want to teleport.
    usage: /worlds