plot-checkout:
  script:
    - plot checkout
  schedule:
    main:
      type: vanilife:match
      year: -1
      month: -1
      day: 1
      hour: 0
      minutes: 10
      second: 0
vwm-reset:
  script:
    - vwm reset
  schedule:
    spring:
      type: vanilife:match
      year: -1
      month: 3
      day: 1
      hour: 0
      minutes: 0
      second: 0
    summer:
      type: vanilife:match
      year: -1
      month: 6
      day: 1
      hour: 0
      minutes: 0
      second: 0
    fall:
      type: vanilife:match
      year: -1
      month: 9
      day: 1
      hour: 0
      minutes: 0
      second: 0
    winter:
      type: vanilife:match
      year: -1
      month: 12
      day: 1
      hour: 0
      minutes: 0
      second: 0
vwm-backup:
  script:
    - vwm backup
  schedule:
    main:
      type: vanilife:match
      year: -1
      month: -1
      day: -1
      hour: 3
      minutes: 0
      second: 0